In [1]:
import requests
import pandas as pd

In [2]:
url = "https://api.openf1.org/v1/sessions"

params = {
    "year": 2024,
    "country_name": "Belgium",
    "session_name": "Race"
}

response = requests.get(url, params=params)

print(response.status_code)
print(response.json())

200
[{'session_key': 9574, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2024-07-28T13:00:00+00:00', 'date_end': '2024-07-28T15:00:00+00:00', 'meeting_key': 1242, 'circuit_key': 7, 'circuit_short_name': 'Spa-Francorchamps', 'country_key': 16, 'country_code': 'BEL', 'country_name': 'Belgium', 'location': 'Spa-Francorchamps', 'gmt_offset': '02:00:00', 'year': 2024, 'is_cancelled': False}]

In [3]:
url = "https://api.openf1.org/v1/laps"

params = {
    "session_key": 9574
}

response = requests.get(url, params=params)

print(response.status_code)

laps_openf1 = pd.DataFrame(response.json())

laps_openf1.head()

200

,meeting_key,session_key,driver_number,lap_number,date_start,duration_sector_1,duration_sector_2,duration_sector_3,i1_speed,i2_speed,is_pit_out_lap,lap_duration,segments_sector_1,segments_sector_2,segments_sector_3,st_speed
0,1242,9574,11,1,2024-07-28T13:03:52.741000+00:00,34.339,50.038,29.491,316.0,201.0,False,113.868,"[2048, 2049, 2049, 2049, 2049, 2049, 2049, 2049]","[2049, 2049, 2049, 2049, 2049, 2049, 2051, 204...","[2049, 2049, 2049, 2049, 2049, 2049, 2049]",310.0
1,1242,9574,44,1,2024-07-28T13:03:52.741000+00:00,34.257,49.406,29.478,326.0,204.0,False,113.141,"[2048, 2049, 2049, 2049, 2049, 2049, 2049, 2049]","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 205...","[2049, 2049, 2049, 2049, 2049, 2049, 2049]",309.0
2,1242,9574,4,1,2024-07-28T13:03:52.741000+00:00,35.290,51.462,29.456,317.0,197.0,False,116.208,"[2048, 2049, 2049, 2049, 2051, 2051, 2049, 2049]","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2049, 2049, 2049]",312.0
3,1242,9574,81,1,2024-07-28T13:03:52.741000+00:00,34.645,50.480,29.643,332.0,203.0,False,114.768,"[2048, 2049, 2049, 2049, 2049, 2049, 2049, 2049]","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2049, 2049, 2049]",302.0
4,1242,9574,63,1,2024-07-28T13:03:52.741000+00:00,34.667,51.125,29.496,331.0,202.0,False,115.288,"[2048, 2049, 2049, 2049, 2049, 2049, 2049, 2051]","[2049, 2049, 2049, 2049, 2049, 2049, 2049, 204...","[2049, 2049, 2049, 2049, 2049, 2049, 2049]",310.0

In [6]:
laps_16_openf1 = laps_openf1[
    laps_openf1["driver_number"] == 16
][
    [
        "driver_number",
        "lap_number",
        "lap_duration",
        "is_pit_out_lap"
    ]
].copy()

laps_16_openf1.head(15)

     driver_number  lap_number  lap_duration  is_pit_out_lap
5               16           1       112.304           False
20              16           2       110.240           False
40              16           3       110.519           False
61              16           4       109.796           False
81              16           5       109.494           False
101             16           6       109.658           False
121             16           7       109.798           False
140             16           8       109.549           False
159             16           9       110.096           False
178             16          10       109.963           False
197             16          11       109.967           False
215             16          12       114.091           False
234             16          13       122.667            True
256             16          14       108.227           False
275             16          15       108.021           False

In [10]:
url = "https://api.jolpi.ca/ergast/f1/2024/12/results/"

response = requests.get(url)

print(response.status_code)

datos_jolpica = response.json()

datos_jolpica

200

{'MRData': {'xmlns': '',
  'series': 'f1',
  'url': 'https://api.jolpi.ca/ergast/f1/2024/12/results/',
  'limit': '30',
  'offset': '0',
  'total': '20',
  'RaceTable': {'season': '2024',
   'round': '12',
   'Races': [{'season': '2024',
     'round': '12',
     'url': 'https://en.wikipedia.org/wiki/2024_British_Grand_Prix',
     'raceName': 'British Grand Prix',
     'Circuit': {'circuitId': 'silverstone',
      'url': 'https://en.wikipedia.org/wiki/Silverstone_Circuit',
      'circuitName': 'Silverstone Circuit',
      'Location': {'lat': '52.0786',
       'long': '-1.01694',
       'locality': 'Silverstone',
       'country': 'UK'}},
     'date': '2024-07-07',
     'time': '14:00:00Z',
     'Results': [{'number': '44',
       'position': '1',
       'positionText': '1',
       'points': '25',
       'Driver': {'driverId': 'hamilton',
        'permanentNumber': '44',
        'code': 'HAM',
        'url': 'http://en.wikipedia.org/wiki/Lewis_Hamilton',
        'givenName': 'Lewis',
        'familyName': 'Hamilton',
        'dateOfBirth': '1985-01-07',
        'nationality': 'British'},
       'Constructor': {'constructorId': 'mercedes',
        'url': 'https://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One',
        'name': 'Mercedes',
        'nationality': 'German'},
       'grid': '2',
       'laps': '52',
       'status': 'Finished',
       'Time': {'millis': '4947059', 'time': '1:22:27.059'},
       'FastestLap': {'rank': '5',
        'lap': '45',
        'Time': {'time': '1:29.438'},
        'AverageSpeed': {'units': 'kph', 'speed': '237.120'}}},
      {'number': '1',
       'position': '2',
       'positionText': '2',
       'points': '18',
       'Driver': {'driverId': 'max_verstappen',
        'permanentNumber': '3',
        'code': 'VER',
        'url': 'http://en.wikipedia.org/wiki/Max_Verstappen',
        'givenName': 'Max',
        'familyName': 'Verstappen',
        'dateOfBirth': '1997-09-30',
        'nationality': 'Dutch'},
       'Constructor': {'constructorId': 'red_bull',
        'url': 'https://en.wikipedia.org/wiki/Red_Bull_Racing',
        'name': 'Red Bull',
        'nationality': 'Austrian'},
       'grid': '4',
       'laps': '52',
       'status': 'Finished',
       'Time': {'millis': '4948524', 'time': '+1.465'},
       'FastestLap': {'rank': '3',
        'lap': '48',
        'Time': {'time': '1:28.952'},
        'AverageSpeed': {'units': 'kph', 'speed': '238.416'}}},
      {'number': '4',
       'position': '3',
       'positionText': '3',
       'points': '15',
       'Driver': {'driverId': 'norris',
        'permanentNumber': '1',
        'code': 'NOR',
        'url': 'http://en.wikipedia.org/wiki/Lando_Norris',
        'givenName': 'Lando',
        'familyName': 'Norris',
        'dateOfBirth': '1999-11-13',
        'nationality': 'British'},
       'Constructor': {'constructorId': 'mclaren',
        'url': 'https://en.wikipedia.org/wiki/McLaren',
        'name': 'McLaren',
        'nationality': 'British'},
       'grid': '3',
       'laps': '52',
       'status': 'Finished',
       'Time': {'millis': '4954606', 'time': '+7.547'},
       'FastestLap': {'rank': '4',
        'lap': '43',
        'Time': {'time': '1:29.262'},
        'AverageSpeed': {'units': 'kph', 'speed': '237.588'}}},
      {'number': '81',
       'position': '4',
       'positionText': '4',
       'points': '12',
       'Driver': {'driverId': 'piastri',
        'permanentNumber': '81',
        'code': 'PIA',
        'url': 'http://en.wikipedia.org/wiki/Oscar_Piastri',
        'givenName': 'Oscar',
        'familyName': 'Piastri',
        'dateOfBirth': '2001-04-06',
        'nationality': 'Australian'},
       'Constructor': {'constructorId': 'mclaren',
        'url': 'https://en.wikipedia.org/wiki/McLaren',
        'name': 'McLaren',
        'nationality': 'British'},
       'grid': '5',
       'laps': '52',
       'status': 'Finished',
       'Time': {'millis': '4959488', 'time': '+12.429'},
       'FastestLap': {'rank': '2',
        'lap': '51',
        'Time': {'time': '1:28.748'},
        'AverageSpeed': {'units': 'kph', 'speed': '238.964'}}},
      {'number': '55',
       'position': '5',
       'positionText': '5',
       'points': '11',
       'Driver': {'driverId': 'sainz',
        'permanentNumber': '55',
        'code': 'SAI',
        'url': 'http://en.wikipedia.org/wiki/Carlos_Sainz_Jr.',
        'givenName': 'Carlos',
        'familyName': 'Sainz',
        'dateOfBirth': '1994-09-01',
        'nationality': 'Spanish'},
       'Constructor': {'constructorId': 'ferrari',
        'url': 'https://en.wikipedia.org/wiki/Scuderia_Ferrari',
        'name': 'Ferrari',
        'nationality': 'Italian'},
       'grid': '7',
       'laps': '52',
       'status': 'Finished',
       'Time': {'millis': '4994377', 'time': '+47.318'},
       'FastestLap': {'rank': '1',
        'lap': '52',
        'Time': {'time': '1:28.293'},
        'AverageSpeed': {'units': 'kph', 'speed': '240.195'}}},
      {'number': '27',
       'position': '6',
       'positionText': '6',
       'points': '8',
       'Driver': {'driverId': 'hulkenberg',
        'permanentNumber': '27',
        'code': 'HUL',
        'url': 'http://en.wikipedia.org/wiki/Nico_H%C3%BClkenberg',
        'givenName': 'Nico',
        'familyName': 'Hülkenberg',
        'dateOfBirth': '1987-08-19',
        'nationality': 'German'},
       'Constructor': {'constructorId': 'haas',
        'url': 'https://en.wikipedia.org/wiki/Haas_F1_Team',
        'name': 'Haas F1 Team',
        'nationality': 'American'},
       'grid': '6',
       'laps': '52',
       'status': 'Finished',
       'Time': {'millis': '5002781', 'time': '+55.722'},
       'FastestLap': {'rank': '10',
        'lap': '43',
        'Time': {'time': '1:29.836'},
        'AverageSpeed': {'units': 'kph', 'speed': '236.070'}}},
      {'number': '18',
       'position': '7',
       'positionText': '7',
       'points': '6',
       'Driver': {'driverId': 'stroll',
        'permanentNumber': '18',
        'code': 'STR',
        'url': 'http://en.wikipedia.org/wiki/Lance_Stroll',
        'givenName': 'Lance',
        'familyName': 'Stroll',
        'dateOfBirth': '1998-10-29',
        'nationality': 'Canadian'},
       'Constructor': {'constructorId': 'aston_martin',
        'url': 'https://en.wikipedia.org/wiki/Aston_Martin_in_Formula_One',
        'name': 'Aston Martin',
        'nationality': 'British'},
       'grid': '8',
       'laps': '52',
       'status': 'Finished',
       'Time': {'millis': '5003628', 'time': '+56.569'},
       'FastestLap': {'rank': '11',
        'lap': '46',
        'Time': {'time': '1:29.897'},
        'AverageSpeed': {'units': 'kph', 'speed': '235.909'}}},
      {'number': '14',
       'position': '8',
       'positionText': '8',
       'points': '4',
       'Driver': {'driverId': 'alonso',
        'permanentNumber': '14',
        'code': 'ALO',
        'url': 'http://en.wikipedia.org/wiki/Fernando_Alonso',
        'givenName': 'Fernando',
        'familyName': 'Alonso',
        'dateOfBirth': '1981-07-29',
        'nationality': 'Spanish'},
       'Constructor': {'constructorId': 'aston_martin',
        'url': 'https://en.wikipedia.org/wiki/Aston_Martin_in_Formula_One',
        'name': 'Aston Martin',
        'nationality': 'British'},
       'grid': '10',
       'laps': '52',
       'status': 'Finished',
       'Time': {'millis': '5010636', 'time': '+1:03.577'},
       'FastestLap': {'rank': '7',
        'lap': '47',
        'Time': {'time': '1:29.710'},
        'AverageSpeed': {'units': 'kph', 'speed': '236.401'}}},
      {'number': '23',
       'position': '9',
       'positionText': '9',
       'points': '2',
       'Driver': {'driverId': 'albon',
        'permanentNumber': '23',
        'code': 'ALB',
        'url': 'http://en.wikipedia.org/wiki/Alexander_Albon',
        'givenName': 'Alexander',
        'familyName': 'Albon',
        'dateOfBirth': '1996-03-23',
        'nationality': 'Thai'},
       'Constructor': {'constructorId': 'williams',
        'url': 'https://en.wikipedia.org/wiki/Williams_Racing',
        'name': 'Williams',
        'nationality': 'British'},
       'grid': '9',
       'laps': '52',
       'status': 'Finished',
       'Time': {'millis': '5015446', 'time': '+1:08.387'},
       'FastestLap': {'rank': '8',
        'lap': '52',
        'Time': {'time': '1:29.718'},
        'AverageSpeed': {'units': 'kph', 'speed': '236.380'}}},
      {'number': '22',
       'position': '10',
       'positionText': '10',
       'points': '1',
       'Driver': {'driverId': 'tsunoda',
        'permanentNumber': '22',
        'code': 'TSU',
        'url': 'http://en.wikipedia.org/wiki/Yuki_Tsunoda',
        'givenName': 'Yuki',
        'familyName': 'Tsunoda',
        'dateOfBirth': '2000-05-11',
        'nationality': 'Japanese'},
       'Constructor': {'constructorId': 'rb',
        'url': 'https://en.wikipedia.org/wiki/Racing_Bulls',
        'name': 'RB F1 Team',
        'nationality': 'Italian'},
       'grid': '13',
       'laps': '52',
       'status': 'Finished',
       'Time': {'millis': '5026362', 'time': '+1:19.303'},
       'FastestLap': {'rank': '14',
        'lap': '43',
        'Time': {'time': '1:30.229'},
        'AverageSpeed': {'units': 'kph', 'speed': '235.041'}}},
      {'number': '2',
       'position': '11',
       'positionText': '11',
       'points': '0',
       'Driver': {'driverId': 'sargeant',
        'permanentNumber': '2',
        'code': 'SAR',
        'url': 'http://en.wikipedia.org/wiki/Logan_Sargeant',
        'givenName': 'Logan',
        'familyName': 'Sargeant',
        'dateOfBirth': '2000-12-31',
        'nationality': 'American'},
       'Constructor': {'constructorId': 'williams',
        'url': 'https://en.wikipedia.org/wiki/Williams_Racing',
        'name': 'Williams',
        'nationality': 'British'},
       'grid': '12',
       'laps': '52',
       'status': 'Finished',
       'Time': {'millis': '5036019', 'time': '+1:28.960'},
       'FastestLap': {'rank': '12',
        'lap': '42',
        'Time': {'time': '1:29.972'},
        'AverageSpeed': {'units': 'kph', 'speed': '235.713'}}},
      {'number': '20',
       'position': '12',
       'positionText': '12',
       'points': '0',
       'Driver': {'driverId': 'kevin_magnussen',
        'permanentNumber': '20',
        'code': 'MAG',
        'url': 'http://en.wikipedia.org/wiki/Kevin_Magnussen',
        'givenName': 'Kevin',
        'familyName': 'Magnussen',
        'dateOfBirth': '1992-10-05',
        'nationality': 'Danish'},
       'Constructor': {'constructorId': 'haas',
        'url': 'https://en.wikipedia.org/wiki/Haas_F1_Team',
        'name': 'Haas F1 Team',
        'nationality': 'American'},
       'grid': '17',
       'laps': '52',
       'status': 'Finished',
       'Time': {'millis': '5037212', 'time': '+1:30.153'},
       'FastestLap': {'rank': '13',
        'lap': '42',
        'Time': {'time': '1:30.093'},
        'AverageSpeed': {'units': 'kph', 'speed': '235.396'}}},
      {'number': '3',
       'position': '13',
       'positionText': '13',
       'points': '0',
       'Driver': {'driverId': 'ricciardo',
        'permanentNumber': '3',
        'code': 'RIC',
        'url': 'http://en.wikipedia.org/wiki/Daniel_Ricciardo',
        'givenName': 'Daniel',
        'familyName': 'Ricciardo',
        'dateOfBirth': '1989-07-01',
        'nationality': 'Australian'},
       'Constructor': {'constructorId': 'rb',
        'url': 'https://en.wikipedia.org/wiki/Racing_Bulls',
        'name': 'RB F1 Team',
        'nationality': 'Italian'},
       'grid': '15',
       'laps': '51',
       'status': 'Lapped',
       'Time': {'millis': '4956996', 'time': '+9.937'},
       'FastestLap': {'rank': '15',
        'lap': '47',
        'Time': {'time': '1:30.735'},
        'AverageSpeed': {'units': 'kph', 'speed': '233.731'}}},
      {'number': '16',
       'position': '14',
       'positionText': '14',
       'points': '0',
       'Driver': {'driverId': 'leclerc',
        'permanentNumber': '16',
        'code': 'LEC',
        'url': 'http://en.wikipedia.org/wiki/Charles_Leclerc',
        'givenName': 'Charles',
        'familyName': 'Leclerc',
        'dateOfBirth': '1997-10-16',
        'nationality': 'Monegasque'},
       'Constructor': {'constructorId': 'ferrari',
        'url': 'https://en.wikipedia.org/wiki/Scuderia_Ferrari',
        'name': 'Ferrari',
        'nationality': 'Italian'},
       'grid': '11',
       'laps': '51',
       'status': 'Lapped',
       'Time': {'millis': '4987532', 'time': '+40.473'},
       'FastestLap': {'rank': '9',
        'lap': '43',
        'Time': {'time': '1:29.748'},
        'AverageSpeed': {'units': 'kph', 'speed': '236.301'}}},
      {'number': '77',
       'position': '15',
       'positionText': '15',
       'points': '0',
       'Driver': {'driverId': 'bottas',
        'permanentNumber': '77',
        'code': 'BOT',
        'url': 'http://en.wikipedia.org/wiki/Valtteri_Bottas',
        'givenName': 'Valtteri',
        'familyName': 'Bottas',
        'dateOfBirth': '1989-08-28',
        'nationality': 'Finnish'},
       'Constructor': {'constructorId': 'sauber',
        'url': 'https://en.wikipedia.org/wiki/Sauber_Motorsport',
        'name': 'Sauber',
        'nationality': 'Swiss'},
       'grid': '16',
       'laps': '51',
       'status': 'Lapped',
       'Time': {'millis': '4988880', 'time': '+41.821'},
       'FastestLap': {'rank': '18',
        'lap': '44',
        'Time': {'time': '1:31.277'},
        'AverageSpeed': {'units': 'kph', 'speed': '232.343'}}},
      {'number': '31',
       'position': '16',
       'positionText': '16',
       'points': '0',
       'Driver': {'driverId': 'ocon',
        'permanentNumber': '31',
        'code': 'OCO',
        'url': 'http://en.wikipedia.org/wiki/Esteban_Ocon',
        'givenName': 'Esteban',
        'familyName': 'Ocon',
        'dateOfBirth': '1996-09-17',
        'nationality': 'French'},
       'Constructor': {'constructorId': 'alpine',
        'url': 'https://en.wikipedia.org/wiki/Alpine_F1_Team',
        'name': 'Alpine F1 Team',
        'nationality': 'French'},
       'grid': '18',
       'laps': '50',
       'status': 'Lapped',
       'Time': {'millis': '4957741', 'time': '+10.682'},
       'FastestLap': {'rank': '16',
        'lap': '46',
        'Time': {'time': '1:30.875'},
        'AverageSpeed': {'units': 'kph', 'speed': '233.371'}}},
      {'number': '11',
       'position': '17',
       'positionText': '17',
       'points': '0',
       'Driver': {'driverId': 'perez',
        'permanentNumber': '11',
        'code': 'PER',
        'url': 'http://en.wikipedia.org/wiki/Sergio_P%C3%A9rez',
        'givenName': 'Sergio',
        'familyName': 'Pérez',
        'dateOfBirth': '1990-01-26',
        'nationality': 'Mexican'},
       'Constructor': {'constructorId': 'red_bull',
        'url': 'https://en.wikipedia.org/wiki/Red_Bull_Racing',
        'name': 'Red Bull',
        'nationality': 'Austrian'},
       'grid': '20',
       'laps': '50',
       'status': 'Lapped',
       'Time': {'millis': '4965064', 'time': '+18.005'},
       'FastestLap': {'rank': '6',
        'lap': '50',
        'Time': {'time': '1:29.707'},
        'AverageSpeed': {'units': 'kph', 'speed': '236.409'}}},
      {'number': '24',
       'position': '18',
       'positionText': '18',
       'points': '0',
       'Driver': {'driverId': 'zhou',
        'permanentNumber': '24',
        'code': 'ZHO',
        'url': 'http://en.wikipedia.org/wiki/Zhou_Guanyu',
        'givenName': 'Guanyu',
        'familyName': 'Zhou',
        'dateOfBirth': '1999-05-30',
        'nationality': 'Chinese'},
       'Constructor': {'constructorId': 'sauber',
        'url': 'https://en.wikipedia.org/wiki/Sauber_Motorsport',
        'name': 'Sauber',
        'nationality': 'Swiss'},
       'grid': '14',
       'laps': '50',
       'status': 'Lapped',
       'Time': {'millis': '5001535', 'time': '+54.476'},
       'FastestLap': {'rank': '17',
        'lap': '43',
        'Time': {'time': '1:31.014'},
        'AverageSpeed': {'units': 'kph', 'speed': '233.014'}}},
      {'number': '63',
       'position': '19',
       'positionText': 'R',
       'points': '0',
       'Driver': {'driverId': 'russell',
        'permanentNumber': '63',
        'code': 'RUS',
        'url': 'http://en.wikipedia.org/wiki/George_Russell_(racing_driver)',
        'givenName': 'George',
        'familyName': 'Russell',
        'dateOfBirth': '1998-02-15',
        'nationality': 'British'},
       'Constructor': {'constructorId': 'mercedes',
        'url': 'https://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One',
        'name': 'Mercedes',
        'nationality': 'German'},
       'grid': '1',
       'laps': '33',
       'status': 'Retired',
       'FastestLap': {'rank': '19',
        'lap': '3',
        'Time': {'time': '1:31.298'},
        'AverageSpeed': {'units': 'kph', 'speed': '232.289'}}},
      {'number': '10',
       'position': '20',
       'positionText': 'W',
       'points': '0',
       'Driver': {'driverId': 'gasly',
        'permanentNumber': '10',
        'code': 'GAS',
        'url': 'http://en.wikipedia.org/wiki/Pierre_Gasly',
        'givenName': 'Pierre',
        'familyName': 'Gasly',
        'dateOfBirth': '1996-02-07',
        'nationality': 'French'},
       'Constructor': {'constructorId': 'alpine',
        'url': 'https://en.wikipedia.org/wiki/Alpine_F1_Team',
        'name': 'Alpine F1 Team',
        'nationality': 'French'},
       'grid': '19',
       'laps': '0',
       'status': 'Did not start'}]}]}}}

In [11]:
resultados = datos_jolpica["MRData"]["RaceTable"]["Races"][0]["Results"]

resultados_jolpica = pd.DataFrame(resultados)

resultados_jolpica.head()

,number,position,positionText,points,Driver,Constructor,grid,laps,status,Time,FastestLap
0,44,1,1,25,"{'driverId': 'hamilton', 'permanentNumber': '4...","{'constructorId': 'mercedes', 'url': 'https://...",2,52,Finished,"{'millis': '4947059', 'time': '1:22:27.059'}","{'rank': '5', 'lap': '45', 'Time': {'time': '1..."
1,1,2,2,18,"{'driverId': 'max_verstappen', 'permanentNumbe...","{'constructorId': 'red_bull', 'url': 'https://...",4,52,Finished,"{'millis': '4948524', 'time': '+1.465'}","{'rank': '3', 'lap': '48', 'Time': {'time': '1..."
2,4,3,3,15,"{'driverId': 'norris', 'permanentNumber': '1',...","{'constructorId': 'mclaren', 'url': 'https://e...",3,52,Finished,"{'millis': '4954606', 'time': '+7.547'}","{'rank': '4', 'lap': '43', 'Time': {'time': '1..."
3,81,4,4,12,"{'driverId': 'piastri', 'permanentNumber': '81...","{'constructorId': 'mclaren', 'url': 'https://e...",5,52,Finished,"{'millis': '4959488', 'time': '+12.429'}","{'rank': '2', 'lap': '51', 'Time': {'time': '1..."
4,55,5,5,11,"{'driverId': 'sainz', 'permanentNumber': '55',...","{'constructorId': 'ferrari', 'url': 'https://e...",7,52,Finished,"{'millis': '4994377', 'time': '+47.318'}","{'rank': '1', 'lap': '52', 'Time': {'time': '1..."

In [12]:
resultados_jolpica_simple = resultados_jolpica[
    ["number", "position", "points", "grid", "laps", "status"]
].copy()

resultados_jolpica_simple

   number position points grid laps         status
0      44        1     25    2   52       Finished
1       1        2     18    4   52       Finished
2       4        3     15    3   52       Finished
3      81        4     12    5   52       Finished
4      55        5     11    7   52       Finished
5      27        6      8    6   52       Finished
6      18        7      6    8   52       Finished
7      14        8      4   10   52       Finished
8      23        9      2    9   52       Finished
9      22       10      1   13   52       Finished
10      2       11      0   12   52       Finished
11     20       12      0   17   52       Finished
12      3       13      0   15   51         Lapped
13     16       14      0   11   51         Lapped
14     77       15      0   16   51         Lapped
15     31       16      0   18   50         Lapped
16     11       17      0   20   50         Lapped
17     24       18      0   14   50         Lapped
18     63       19      0    1   33        Retired
19     10       20      0   19    0  Did not start