In [ ]:
import livef1
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
session = livef1.get_session(
    season=2024,
    meeting_identifier="Spa",
    session_identifier="Race"
)

print(session)

13:45:20 - livef1 - Driver standings have been loaded and saved to 'season.driverStandings'.
13:45:21 - livef1 - Constructor standings have been loaded and saved to 'season.constructorStandings'.
13:45:21 - livef1 - Selected meeting/session is:
	Meeting Offname : FORMULA 1 ROLEX BELGIAN GRAND PRIX 2024
	Meeting Name : Belgian Grand Prix
	Meeting Circuit Shortname : Spa-Francorchamps
13:45:21 - livef1 - Got the meeting.
13:45:21 - livef1 - Selected meeting/session is:
	session_name : Race
13:45:21 - livef1 - The session was received successfully.
13:45:22 - livef1 - Fetching drivers.
13:45:23 - livef1 - Driver standings have been loaded and saved to 'session.driverStandings'.
13:45:23 - livef1 - Constructor standings have been loaded and saved to 'session.constructorStandings'.

<livef1.models.session.Session object at 0x0000022CCAE64550>

In [3]:
position_data = session.get_data(
    dataNames="Position.z"
)
print(position_data.head())

13:45:26 - livef1 - 'Position.z' has been fetched and parsed

  SessionKey              timestamp                           Utc DriverNo  \
0       9574 0 days 00:01:45.570000  2024-07-28T12:10:22.7877313Z        1
1       9574 0 days 00:01:45.570000  2024-07-28T12:10:22.7877313Z        2
2       9574 0 days 00:01:45.570000  2024-07-28T12:10:22.7877313Z        3
3       9574 0 days 00:01:45.570000  2024-07-28T12:10:22.7877313Z        4
4       9574 0 days 00:01:45.570000  2024-07-28T12:10:22.7877313Z       10

    Status    X    Y    Z
0  OnTrack  0.0  0.0  0.0
1  OnTrack  0.0  0.0  0.0
2  OnTrack  0.0  0.0  0.0
3  OnTrack  0.0  0.0  0.0
4  OnTrack  0.0  0.0  0.0

In [4]:
position_data.info()
print("Registros:", len(position_data))
print("Pilotos:", position_data["DriverNo"].nunique())

<class 'pandas.DataFrame'>
RangeIndex: 625020 entries, 0 to 625019
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   SessionKey  625020 non-null  category
 1   timestamp   625020 non-null  timedelta64[us]
 2   Utc         625020 non-null  str
 3   DriverNo    625020 non-null  category
 4   Status      625020 non-null  category
 5   X           625020 non-null  float32
 6   Y           625020 non-null  float32
 7   Z           625020 non-null  float32
dtypes: category(3), float32(3), str(1), timedelta64[us](1)
memory usage: 18.5 MB
Registros: 625020
Pilotos: 20

In [5]:
timing = session.get_data(dataNames="TimingData")
print(type(timing))
print(timing.head())

13:45:31 - livef1 - 'TimingData' has been fetched and parsed

<class 'pandas.DataFrame'>
  SessionKey              timestamp DriverNo GapToLeader  \
0       9574 0 days 00:00:03.734000       16
1       9574 0 days 00:00:03.734000       11
2       9574 0 days 00:00:03.734000       44
3       9574 0 days 00:00:03.734000        4
4       9574 0 days 00:00:03.734000       81

  IntervalToPositionAhead_Value IntervalToPositionAhead_Catching  Line  \
0                                                          False   1.0
1                                                          False   2.0
2                                                          False   3.0
3                                                          False   4.0
4                                                          False   5.0

  Position ShowPosition RacingNumber  ... Sectors_2_Segments_6_Status  \
0        1         True           16  ...                         NaN
1        2         True           11  ...                         NaN
2        3         True           44  ...                         NaN
3        4         True            4  ...                         NaN
4        5         True           81  ...                         NaN

  Sectors_1_PreviousValue NumberOfLaps Sectors_2_PreviousValue  \
0                     NaN          NaN                     NaN
1                     NaN          NaN                     NaN
2                     NaN          NaN                     NaN
3                     NaN          NaN                     NaN
4                     NaN          NaN                     NaN

  Sectors_0_Value Sectors_0_OverallFastest Sectors_0_PersonalFastest  \
0             NaN                      NaN                       NaN
1             NaN                      NaN                       NaN
2             NaN                      NaN                       NaN
3             NaN                      NaN                       NaN
4             NaN                      NaN                       NaN

   Sectors_0_PreviousValue BestLapTime_Lap NumberOfPitStops
0                      NaN             NaN              NaN
1                      NaN             NaN              NaN
2                      NaN             NaN              NaN
3                      NaN             NaN              NaN
4                      NaN             NaN              NaN

[5 rows x 99 columns]

In [6]:
tyres = session.get_data(dataNames="TyreStintSeries")
print(tyres.head())

13:45:32 - livef1 - 'TyreStintSeries' has been fetched and parsed

   session_key              timestamp DriverNo PitCount Compound   New  \
0         9574 0 days 00:48:25.685000       14        0   MEDIUM  true
1         9574 0 days 00:48:30.766000       10        0   MEDIUM  true
2         9574 0 days 00:48:30.766000       18        0     HARD  true
3         9574 0 days 00:48:30.766000       20        0   MEDIUM  true
4         9574 0 days 00:48:30.766000       22        0   MEDIUM  true

  TyresNotChanged  TotalLaps  StartLaps
0               0        0.0        0.0
1               0        0.0        0.0
2               0        0.0        0.0
3               0        0.0        0.0
4               0        0.0        0.0

In [7]:
print(timing[
    ["DriverNo",
     "timestamp",
     "NumberOfLaps",
     "Position",
     "LastLapTime_Value",
     "GapToLeader",
     "IntervalToPositionAhead_Value"]
].head(20))
print(timing["NumberOfLaps"].unique()[:30])

   DriverNo              timestamp  NumberOfLaps Position LastLapTime_Value  \
0        16 0 days 00:00:03.734000           NaN        1
1        11 0 days 00:00:03.734000           NaN        2
2        44 0 days 00:00:03.734000           NaN        3
3         4 0 days 00:00:03.734000           NaN        4
4        81 0 days 00:00:03.734000           NaN        5
5        63 0 days 00:00:03.734000           NaN        6
6        55 0 days 00:00:03.734000           NaN        7
7        14 0 days 00:00:03.734000           NaN        8
8        31 0 days 00:00:03.734000           NaN        9
9        23 0 days 00:00:03.734000           NaN       10
10        1 0 days 00:00:03.734000           NaN       11
11       10 0 days 00:00:03.734000           NaN       12
12        3 0 days 00:00:03.734000           NaN       13
13       77 0 days 00:00:03.734000           NaN       14
14       18 0 days 00:00:03.734000           NaN       15
15       27 0 days 00:00:03.734000           NaN       16
16       20 0 days 00:00:03.734000           NaN       17
17        2 0 days 00:00:03.734000           NaN       18
18       24 0 days 00:00:03.734000           NaN       19
19       22 0 days 00:00:03.734000           NaN       20

   GapToLeader IntervalToPositionAhead_Value
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
[nan  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]

In [8]:
timing_laps = timing[
    timing["NumberOfLaps"].notna()
]

print(timing_laps[
    ["DriverNo",
     "timestamp",
     "NumberOfLaps",
     "Position",
     "LastLapTime_Value",
     "GapToLeader",
     "IntervalToPositionAhead_Value"]
].head(30))

print(timing_laps["NumberOfLaps"].value_counts().sort_index().head(20))

     DriverNo              timestamp  NumberOfLaps Position LastLapTime_Value  \
3512       16 0 days 00:57:07.067000           1.0      NaN               NaN
3523       44 0 days 00:57:07.904000           1.0      NaN               NaN
3530       11 0 days 00:57:08.631000           1.0      NaN               NaN
3537       81 0 days 00:57:09.531000           1.0      NaN               NaN
3542       63 0 days 00:57:10.051000           1.0      NaN               NaN
3550       55 0 days 00:57:10.473000           1.0      NaN               NaN
3557        4 0 days 00:57:10.971000           1.0      NaN               NaN
3566       14 0 days 00:57:11.748000           1.0      NaN               NaN
3573        1 0 days 00:57:12.248000           1.0      NaN               NaN
3582       23 0 days 00:57:12.513000           1.0      NaN               NaN
3588       31 0 days 00:57:13.070000           1.0      NaN               NaN
3592       10 0 days 00:57:13.725000           1.0      NaN               NaN
3598       77 0 days 00:57:13.923000           1.0      NaN               NaN
3603        3 0 days 00:57:14.461000           1.0      NaN               NaN
3607       18 0 days 00:57:14.684000           1.0      NaN               NaN
3616       27 0 days 00:57:15.314000           1.0      NaN               NaN
3619       20 0 days 00:57:15.868000           1.0      NaN               NaN
3626       24 0 days 00:57:16.380000           1.0      NaN               NaN
3633       22 0 days 00:57:16.875000           1.0      NaN               NaN
3638        2 0 days 00:57:17.310000           1.0      NaN               NaN
4742       16 0 days 00:58:57.351000           2.0      NaN          1:50.240
4747       44 0 days 00:58:57.644000           2.0      NaN          1:49.849
4760       11 0 days 00:58:58.806000           2.0      NaN          1:50.240
4766       81 0 days 00:58:59.549000           2.0      NaN          1:50.164
4772       63 0 days 00:59:00.167000           2.0      NaN          1:50.160
4778       55 0 days 00:59:00.782000           2.0      NaN          1:50.260
4783        4 0 days 00:59:01.395000           2.0      NaN          1:50.504
4795        1 0 days 00:59:02.276000           2.0      NaN          1:49.828
4802       14 0 days 00:59:03.109000           2.0      NaN          1:51.316
4810       23 0 days 00:59:03.799000           2.0      NaN          1:51.283

     GapToLeader IntervalToPositionAhead_Value
3512         NaN                           NaN
3523         NaN                           NaN
3530         NaN                           NaN
3537         NaN                           NaN
3542         NaN                           NaN
3550         NaN                           NaN
3557         NaN                           NaN
3566         NaN                           NaN
3573         NaN                           NaN
3582         NaN                           NaN
3588         NaN                           NaN
3592         NaN                           NaN
3598         NaN                           NaN
3603         NaN                           NaN
3607         NaN                           NaN
3616         NaN                           NaN
3619         NaN                           NaN
3626         NaN                           NaN
3633         NaN                           NaN
3638         NaN                           NaN
4742         NaN                           NaN
4747         NaN                           NaN
4760         NaN                           NaN
4766         NaN                           NaN
4772         NaN                           NaN
4778         NaN                           NaN
4783         NaN                           NaN
4795         NaN                           NaN
4802         NaN                           NaN
4810         NaN                           NaN
NumberOfLaps
1.0     20
2.0     20
3.0     20
4.0     20
5.0     20
6.0     19
7.0     19
8.0     19
9.0     19
10.0    19
11.0    19
12.0    19
13.0    19
14.0    19
15.0    19
16.0    19
17.0    19
18.0    19
19.0    19
20.0    19
Name: count, dtype: int64

In [9]:
print("Pilotos:", timing_laps["DriverNo"].nunique())
print("Vuelta máxima:", timing_laps["NumberOfLaps"].max())
print("Registros:", len(timing_laps))

vueltas = timing_laps[
    [
        "DriverNo",
        "timestamp",
        "NumberOfLaps",
        "Position",
        "LastLapTime_Value",
        "GapToLeader",
        "IntervalToPositionAhead_Value"
    ]
].copy()

vueltas = vueltas.rename(columns={
    "DriverNo": "piloto",
    "timestamp": "timestamp",
    "NumberOfLaps": "vuelta",
    "Position": "posicion",
    "LastLapTime_Value": "tiempo_vuelta",
    "GapToLeader": "gap_lider",
    "IntervalToPositionAhead_Value": "gap_adelante"
})

print(vueltas.head())

Pilotos: 20
Vuelta máxima: 44.0
Registros: 841
     piloto              timestamp  vuelta posicion tiempo_vuelta gap_lider  \
3512     16 0 days 00:57:07.067000     1.0      NaN           NaN       NaN
3523     44 0 days 00:57:07.904000     1.0      NaN           NaN       NaN
3530     11 0 days 00:57:08.631000     1.0      NaN           NaN       NaN
3537     81 0 days 00:57:09.531000     1.0      NaN           NaN       NaN
3542     63 0 days 00:57:10.051000     1.0      NaN           NaN       NaN

     gap_adelante
3512          NaN
3523          NaN
3530          NaN
3537          NaN
3542          NaN

In [10]:
vueltas = vueltas[
    vueltas["tiempo_vuelta"].notna()
].copy()

print(vueltas.head())
print("Registros:", len(vueltas))

     piloto              timestamp  vuelta posicion tiempo_vuelta gap_lider  \
4742     16 0 days 00:58:57.351000     2.0      NaN      1:50.240       NaN
4747     44 0 days 00:58:57.644000     2.0      NaN      1:49.849       NaN
4760     11 0 days 00:58:58.806000     2.0      NaN      1:50.240       NaN
4766     81 0 days 00:58:59.549000     2.0      NaN      1:50.164       NaN
4772     63 0 days 00:59:00.167000     2.0      NaN      1:50.160       NaN

     gap_adelante
4742          NaN
4747          NaN
4760          NaN
4766          NaN
4772          NaN
Registros: 819

In [11]:
print(
    vueltas[vueltas["vuelta"] == 2][
        ["piloto", "vuelta", "posicion", "tiempo_vuelta",
         "gap_lider", "gap_adelante"]
    ]
)

print(
    vueltas.groupby("vuelta")["piloto"].nunique().head(15)
)

     piloto  vuelta posicion tiempo_vuelta gap_lider gap_adelante
4742     16     2.0      NaN      1:50.240       NaN          NaN
4747     44     2.0      NaN      1:49.849       NaN          NaN
4760     11     2.0      NaN      1:50.240       NaN          NaN
4766     81     2.0      NaN      1:50.164       NaN          NaN
4772     63     2.0      NaN      1:50.160       NaN          NaN
4778     55     2.0      NaN      1:50.260       NaN          NaN
4783      4     2.0      NaN      1:50.504       NaN          NaN
4795      1     2.0      NaN      1:49.828       NaN          NaN
4802     14     2.0      NaN      1:51.316       NaN          NaN
4810     23     2.0      NaN      1:51.283       NaN          NaN
4819     31     2.0      NaN      1:51.312       NaN          NaN
4829     10     2.0      NaN      1:51.273       NaN          NaN
4833     77     2.0      NaN      1:51.452       NaN          NaN
4838      3     2.0      NaN      1:51.541       NaN          NaN
4843     18     2.0      NaN      1:51.654       NaN          NaN
4846     27     2.0      NaN      1:51.800       NaN          NaN
4851     20     2.0      NaN      1:51.732       NaN          NaN
4864     24     2.0      NaN      1:52.099       NaN          NaN
4870     22     2.0      NaN      1:52.391       NaN          NaN
4876      2     2.0      NaN      1:52.288       NaN          NaN
vuelta
2.0     20
3.0     20
4.0     20
5.0     20
6.0     19
7.0     19
8.0     19
9.0     18
10.0    19
11.0    19
12.0    19
13.0    19
14.0    19
15.0    19
16.0    19
Name: piloto, dtype: int64

In [12]:
print(tyres.columns.tolist())
print(tyres.info())
print(
    tyres[
        ["DriverNo", "timestamp", "PitCount", "Compound",
         "New", "TyresNotChanged", "TotalLaps", "StartLaps"]
    ].head(30)
)

['session_key', 'timestamp', 'DriverNo', 'PitCount', 'Compound', 'New', 'TyresNotChanged', 'TotalLaps', 'StartLaps']
<class 'pandas.DataFrame'>
RangeIndex: 909 entries, 0 to 908
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   session_key      909 non-null    int64
 1   timestamp        909 non-null    timedelta64[us]
 2   DriverNo         909 non-null    category
 3   PitCount         909 non-null    str
 4   Compound         68 non-null     category
 5   New              67 non-null     str
 6   TyresNotChanged  67 non-null     str
 7   TotalLaps        899 non-null    float64
 8   StartLaps        58 non-null     float64
dtypes: category(2), float64(2), int64(1), str(3), timedelta64[us](1)
memory usage: 51.8 KB
None
   DriverNo              timestamp PitCount Compound   New TyresNotChanged  \
0        14 0 days 00:48:25.685000        0   MEDIUM  true               0
1        10 0 days 00:48:30.766000        0   MEDIUM  true               0
2        18 0 days 00:48:30.766000        0     HARD  true               0
3        20 0 days 00:48:30.766000        0   MEDIUM  true               0
4        22 0 days 00:48:30.766000        0   MEDIUM  true               0
5        27 0 days 00:48:30.766000        0   MEDIUM  true               0
6        31 0 days 00:48:30.766000        0   MEDIUM  true               0
7        44 0 days 00:48:30.766000        0   MEDIUM  true               0
8        63 0 days 00:48:30.766000        0   MEDIUM  true               0
9         1 0 days 00:48:35.844000        0   MEDIUM  true               0
10        3 0 days 00:48:35.844000        0     SOFT  true               0
11       11 0 days 00:48:35.844000        0   MEDIUM  true               0
12       16 0 days 00:48:35.844000        0   MEDIUM  true               0
13       18 0 days 00:48:35.844000        0   MEDIUM   NaN             NaN
14       24 0 days 00:48:35.844000        0     HARD  true               0
15       55 0 days 00:48:35.844000        0     HARD  true               0
16       77 0 days 00:48:35.844000        0   MEDIUM  true               0
17        2 0 days 00:48:40.886000        0   MEDIUM  true               0
18        4 0 days 00:48:40.886000        0   MEDIUM  true               0
19       23 0 days 00:48:40.886000        0   MEDIUM  true               0
20       81 0 days 00:48:40.886000        0   MEDIUM  true               0
21       11 0 days 00:57:10.988000        0      NaN   NaN             NaN
22       16 0 days 00:57:10.988000        0      NaN   NaN             NaN
23       44 0 days 00:57:10.988000        0      NaN   NaN             NaN
24       55 0 days 00:57:10.988000        0      NaN   NaN             NaN
25       63 0 days 00:57:10.988000        0      NaN   NaN             NaN
26       81 0 days 00:57:10.988000        0      NaN   NaN             NaN
27        1 0 days 00:57:15.978000        0      NaN   NaN             NaN
28        3 0 days 00:57:15.978000        0      NaN   NaN             NaN
29        4 0 days 00:57:15.978000        0      NaN   NaN             NaN

    TotalLaps  StartLaps
0         0.0        0.0
1         0.0        0.0
2         0.0        0.0
3         0.0        0.0
4         0.0        0.0
5         0.0        0.0
6         0.0        0.0
7         0.0        0.0
8         0.0        0.0
9         0.0        0.0
10        0.0        0.0
11        0.0        0.0
12        0.0        0.0
13        NaN        NaN
14        0.0        0.0
15        0.0        0.0
16        0.0        0.0
17        0.0        0.0
18        0.0        0.0
19        0.0        0.0
20        0.0        0.0
21        1.0        NaN
22        1.0        NaN
23        1.0        NaN
24        1.0        NaN
25        1.0        NaN
26        1.0        NaN
27        1.0        NaN
28        1.0        NaN
29        1.0        NaN

In [13]:
tyres_stints = tyres[
    tyres["Compound"].notna()
].copy()

print(tyres_stints[
    ["DriverNo", "timestamp", "PitCount", "Compound",
     "New", "TyresNotChanged", "TotalLaps", "StartLaps"]
].to_string(index=False))

print(
    tyres_stints.groupby("DriverNo")["Compound"].count()
)

print(
    tyres_stints["Compound"].value_counts()
)

DriverNo              timestamp PitCount Compound   New TyresNotChanged  TotalLaps  StartLaps
      14 0 days 00:48:25.685000        0   MEDIUM  true               0        0.0        0.0
      10 0 days 00:48:30.766000        0   MEDIUM  true               0        0.0        0.0
      18 0 days 00:48:30.766000        0     HARD  true               0        0.0        0.0
      20 0 days 00:48:30.766000        0   MEDIUM  true               0        0.0        0.0
      22 0 days 00:48:30.766000        0   MEDIUM  true               0        0.0        0.0
      27 0 days 00:48:30.766000        0   MEDIUM  true               0        0.0        0.0
      31 0 days 00:48:30.766000        0   MEDIUM  true               0        0.0        0.0
      44 0 days 00:48:30.766000        0   MEDIUM  true               0        0.0        0.0
      63 0 days 00:48:30.766000        0   MEDIUM  true               0        0.0        0.0
       1 0 days 00:48:35.844000        0   MEDIUM  true               0        0.0        0.0
       3 0 days 00:48:35.844000        0     SOFT  true               0        0.0        0.0
      11 0 days 00:48:35.844000        0   MEDIUM  true               0        0.0        0.0
      16 0 days 00:48:35.844000        0   MEDIUM  true               0        0.0        0.0
      18 0 days 00:48:35.844000        0   MEDIUM   NaN             NaN        NaN        NaN
      24 0 days 00:48:35.844000        0     HARD  true               0        0.0        0.0
      55 0 days 00:48:35.844000        0     HARD  true               0        0.0        0.0
      77 0 days 00:48:35.844000        0   MEDIUM  true               0        0.0        0.0
       2 0 days 00:48:40.886000        0   MEDIUM  true               0        0.0        0.0
       4 0 days 00:48:40.886000        0   MEDIUM  true               0        0.0        0.0
      23 0 days 00:48:40.886000        0   MEDIUM  true               0        0.0        0.0
      81 0 days 00:48:40.886000        0   MEDIUM  true               0        0.0        0.0
      27 0 days 01:08:51.008000        1     HARD  true               0        0.0        0.0
       3 0 days 01:10:36.032000        1  UNKNOWN false               1        0.0        0.0
      23 0 days 01:10:36.032000        1   MEDIUM  true               0        0.0        0.0
       3 0 days 01:10:41.051000        1   MEDIUM  true               0        NaN        NaN
       2 0 days 01:10:46.040000        1   MEDIUM  true               0        0.0        0.0
      10 0 days 01:12:26.062000        1  UNKNOWN false               1        0.0        0.0
      10 0 days 01:12:31.061000        1     HARD  true               0        NaN        NaN
      63 0 days 01:14:06.069000        1     HARD  true               0        0.0        0.0
       1 0 days 01:14:11.154000        1  UNKNOWN false               1        0.0        0.0
       1 0 days 01:14:16.084000        1     HARD  true               0        NaN        NaN
      44 0 days 01:15:51.109000        1     HARD  true               0        0.0        0.0
      11 0 days 01:15:56.109000        1   MEDIUM  true               0        0.0        0.0
      81 0 days 01:15:56.109000        1  UNKNOWN false               1        0.0        0.0
      81 0 days 01:16:01.119000        1     HARD  true               0        NaN        NaN
      77 0 days 01:16:11.148000        1     HARD  true               0        0.0        0.0
      16 0 days 01:17:41.193000        1     HARD  true               0        0.0        0.0
      18 0 days 01:18:01.185000        1  UNKNOWN false               1        0.0        0.0
      31 0 days 01:18:01.185000        1     HARD  true               0        0.0        0.0
      18 0 days 01:18:06.171000        1     HARD  true               0        NaN        NaN
      14 0 days 01:19:46.232000        1     HARD  true               0        0.0        0.0
       4 0 days 01:23:16.227000        1     HARD  true               0        0.0        0.0
      22 0 days 01:23:46.190000        1     HARD false               0        1.0        1.0
      20 0 days 01:27:21.219000        1     HARD  true               0        0.0        0.0
      55 0 days 01:32:21.194000        1   MEDIUM  true               0        0.0        0.0
      27 0 days 01:33:01.209000        2   MEDIUM  true               0        0.0        0.0
      11 0 days 01:34:21.213000        2     HARD  true               0        0.0        0.0
       3 0 days 01:34:41.216000        2     HARD false               0        1.0        1.0
      23 0 days 01:38:21.235000        2     HARD  true               0        0.0        0.0
       2 0 days 01:40:36.251000        2     HARD  true               0        0.0        0.0
      16 0 days 01:41:26.266000        2     HARD  true               0        0.0        0.0
      44 0 days 01:43:11.276000        2  UNKNOWN false               1        0.0        0.0
      44 0 days 01:43:16.278000        2     HARD  true               0        NaN        NaN
       1 0 days 01:47:01.313000        2   MEDIUM  true               0        0.0        0.0
      55 0 days 01:47:06.300000        2     HARD  true               0        0.0        0.0
      10 0 days 01:47:36.321000        2     HARD  true               0        0.0        0.0
       4 0 days 01:48:46.369000        2     HARD  true               0        0.0        0.0
      81 0 days 01:50:26.335000        2  UNKNOWN false               1        0.0        0.0
      81 0 days 01:50:31.346000        2     HARD  true               0        NaN        NaN
      31 0 days 01:51:01.347000        2  UNKNOWN false               1        0.0        0.0
      31 0 days 01:51:06.349000        2     HARD  true               0        NaN        NaN
      77 0 days 02:00:21.385000        2   MEDIUM  true               0        0.0        0.0
      11 0 days 02:12:26.483000        3  UNKNOWN false               1        0.0        0.0
      11 0 days 02:12:31.473000        3     SOFT  true               0        NaN        NaN
      14 0 days 02:16:31.507000        2   MEDIUM  true               0        0.0        0.0
       3 0 days 02:16:36.516000        3     SOFT  true               0        0.0        0.0
      18 0 days 02:16:46.512000        2   MEDIUM  true               0        0.0        0.0
      22 0 days 02:16:56.529000        2     SOFT  true               0        0.0        0.0
DriverNo
1     4
10    4
11    5
14    3
16    3
18    5
2     3
20    2
22    3
23    3
24    1
27    3
3     5
31    4
4     3
44    4
55    3
63    2
77    3
81    5
Name: Compound, dtype: int64
Compound
HARD       28
MEDIUM     27
UNKNOWN     9
SOFT        4
Name: count, dtype: int64

In [14]:
tyres_stints = tyres_stints.sort_values(
    ["DriverNo", "timestamp"]
).copy()

tyres_stints[
    ["DriverNo", "timestamp", "PitCount", "Compound"]
].head(20)

    DriverNo              timestamp PitCount Compound
9          1 0 days 00:48:35.844000        0   MEDIUM
220        1 0 days 01:14:11.154000        1  UNKNOWN
223        1 0 days 01:14:16.084000        1     HARD
579        1 0 days 01:47:01.313000        2   MEDIUM
1         10 0 days 00:48:30.766000        0   MEDIUM
201       10 0 days 01:12:26.062000        1  UNKNOWN
203       10 0 days 01:12:31.061000        1     HARD
591       10 0 days 01:47:36.321000        2     HARD
11        11 0 days 00:48:35.844000        0   MEDIUM
240       11 0 days 01:15:56.109000        1   MEDIUM
439       11 0 days 01:34:21.213000        2     HARD
854       11 0 days 02:12:26.483000        3  UNKNOWN
856       11 0 days 02:12:31.473000        3     SOFT
0         14 0 days 00:48:25.685000        0   MEDIUM
288       14 0 days 01:19:46.232000        1     HARD
902       14 0 days 02:16:31.507000        2   MEDIUM
12        16 0 days 00:48:35.844000        0   MEDIUM
257       16 0 days 01:17:41.193000        1     HARD
519       16 0 days 01:41:26.266000        2     HARD
2         18 0 days 00:48:30.766000        0     HARD

In [15]:
print("Pilotos:", tyres_stints["DriverNo"].nunique())
print("Stints:", len(tyres_stints))
print("Compuestos:")
print(tyres_stints["Compound"].value_counts())

Pilotos: 20
Stints: 68
Compuestos:
Compound
HARD       28
MEDIUM     27
UNKNOWN     9
SOFT        4
Name: count, dtype: int64

In [21]:
tyres_known = tyres_stints[
    tyres_stints["Compound"] != "UNKNOWN"
].copy()

tyres_known = tyres_known.rename(columns={
    "DriverNo": "piloto"
})

tablas = []

for piloto in vueltas["piloto"].unique():

    vueltas_piloto = vueltas[
        vueltas["piloto"] == piloto
    ].sort_values("timestamp").copy()

    tyres_piloto = tyres_known[
        tyres_known["piloto"] == piloto
    ].sort_values("timestamp").copy()

    vueltas_piloto = pd.merge_asof(
        vueltas_piloto,
        tyres_piloto[
            ["timestamp", "PitCount", "Compound"]
        ],
        on="timestamp",
        direction="backward"
    )

    vueltas_piloto["piloto"] = piloto

    tablas.append(vueltas_piloto)

vueltas_con_neumaticos = pd.concat(
    tablas,
    ignore_index=True
)

vueltas_con_neumaticos = vueltas_con_neumaticos.sort_values(
    ["piloto", "vuelta"]
).reset_index(drop=True)

print(vueltas_con_neumaticos.head(20))

   piloto              timestamp  vuelta posicion tiempo_vuelta gap_lider  \
0       1 0 days 00:59:02.276000     2.0      NaN      1:49.828       NaN
1       1 0 days 01:00:52.281000     3.0      NaN      1:50.141       NaN
2       1 0 days 01:02:42.389000     4.0      NaN      1:50.055       NaN
3       1 0 days 01:04:32.571000     5.0      NaN      1:50.138       NaN
4       1 0 days 01:06:22.601000     6.0      NaN      1:50.073       NaN
5       1 0 days 01:08:12.761000     7.0      NaN      1:50.146       NaN
6       1 0 days 01:10:02.852000     8.0      NaN      1:50.094       NaN
7       1 0 days 01:11:53.454000     9.0      NaN      1:50.609       NaN
8       1 0 days 01:13:48.087000    10.0      NaN      1:54.655       NaN
9       1 0 days 01:15:50.871000    11.0      NaN      2:02.789       NaN
10      1 0 days 01:17:39.283000    12.0      NaN      1:48.403       NaN
11      1 0 days 01:19:27.704000    13.0      NaN      1:48.431       NaN
12      1 0 days 01:21:15.771000    14.0      NaN      1:48.153       NaN
13      1 0 days 01:23:04.191000    15.0      NaN      1:48.229       NaN
14      1 0 days 01:24:52.635000    16.0      NaN      1:48.509       NaN
15      1 0 days 01:26:41.166000    17.0      NaN      1:48.431       NaN
16      1 0 days 01:28:29.919000    18.0      NaN      1:48.896       NaN
17      1 0 days 01:30:18.521000    19.0      NaN      1:48.578       NaN
18      1 0 days 01:32:07.722000    20.0      NaN      1:49.134       NaN
19      1 0 days 01:33:56.860000    21.0      NaN      1:49.273       NaN

   gap_adelante PitCount Compound
0           NaN        0   MEDIUM
1           NaN        0   MEDIUM
2           NaN        0   MEDIUM
3           NaN        0   MEDIUM
4           NaN        0   MEDIUM
5           NaN        0   MEDIUM
6           NaN        0   MEDIUM
7           NaN        0   MEDIUM
8           NaN        0   MEDIUM
9           NaN        1     HARD
10          NaN        1     HARD
11          NaN        1     HARD
12          NaN        1     HARD
13          NaN        1     HARD
14          NaN        1     HARD
15          NaN        1     HARD
16          NaN        1     HARD
17          NaN        1     HARD
18          NaN        1     HARD
19          NaN        1     HARD

In [28]:
vueltas_con_neumaticos[
    vueltas_con_neumaticos["piloto"] == "1"
][
    ["piloto", "vuelta", "tiempo_vuelta", "PitCount", "Compound"]
].head(20)

      piloto  vuelta tiempo_vuelta PitCount Compound
4795       1     2.0      1:49.828        0   MEDIUM
5973       1     3.0      1:50.141        0   MEDIUM
7145       1     4.0      1:50.055        0   MEDIUM
8333       1     5.0      1:50.138        0   MEDIUM
9502       1     6.0      1:50.073        0   MEDIUM
10630      1     7.0      1:50.146        0   MEDIUM
11749      1     8.0      1:50.094        0   MEDIUM
12870      1     9.0      1:50.609        0   MEDIUM
14046      1    10.0      1:54.655        0   MEDIUM
15321      1    11.0      2:02.789        1     HARD
16467      1    12.0      1:48.403        1     HARD
17622      1    13.0      1:48.431        1     HARD
18762      1    14.0      1:48.153        1     HARD
19883      1    15.0      1:48.229        1     HARD
21010      1    16.0      1:48.509        1     HARD
22145      1    17.0      1:48.431        1     HARD
23275      1    18.0      1:48.896        1     HARD
24400      1    19.0      1:48.578        1     HARD
25532      1    20.0      1:49.134        1     HARD
26655      1    21.0      1:49.273        1     HARD

In [29]:
def tiempo_a_segundos(t):
    if pd.isna(t):
        return pd.NA
    
    minutos, segundos = str(t).split(":")
    return int(minutos) * 60 + float(segundos)


vueltas_con_neumaticos["tiempo_seg"] = (
    vueltas_con_neumaticos["tiempo_vuelta"]
    .apply(tiempo_a_segundos)
)

vueltas_con_neumaticos[
    ["piloto", "vuelta", "tiempo_vuelta", "tiempo_seg", "PitCount", "Compound"]
].head(20)

      piloto  vuelta tiempo_vuelta  tiempo_seg PitCount Compound
4795       1     2.0      1:49.828     109.828        0   MEDIUM
5973       1     3.0      1:50.141     110.141        0   MEDIUM
7145       1     4.0      1:50.055     110.055        0   MEDIUM
8333       1     5.0      1:50.138     110.138        0   MEDIUM
9502       1     6.0      1:50.073     110.073        0   MEDIUM
10630      1     7.0      1:50.146     110.146        0   MEDIUM
11749      1     8.0      1:50.094     110.094        0   MEDIUM
12870      1     9.0      1:50.609     110.609        0   MEDIUM
14046      1    10.0      1:54.655     114.655        0   MEDIUM
15321      1    11.0      2:02.789     122.789        1     HARD
16467      1    12.0      1:48.403     108.403        1     HARD
17622      1    13.0      1:48.431     108.431        1     HARD
18762      1    14.0      1:48.153     108.153        1     HARD
19883      1    15.0      1:48.229     108.229        1     HARD
21010      1    16.0      1:48.509     108.509        1     HARD
22145      1    17.0      1:48.431     108.431        1     HARD
23275      1    18.0      1:48.896     108.896        1     HARD
24400      1    19.0      1:48.578     108.578        1     HARD
25532      1    20.0      1:49.134     109.134        1     HARD
26655      1    21.0      1:49.273     109.273        1     HARD

In [32]:
vueltas_con_neumaticos = vueltas_con_neumaticos.sort_values(
    ["piloto", "PitCount", "vuelta"]
).copy()

vueltas_con_neumaticos["vueltas_neumatico"] = (
    vueltas_con_neumaticos
    .groupby(["piloto", "PitCount"])
    .cumcount() + 1
)

vueltas_con_neumaticos[
    [
        "piloto",
        "vuelta",
        "Compound",
        "PitCount",
        "vueltas_neumatico",
        "tiempo_seg"
    ]
].head(20)

      piloto  vuelta Compound PitCount  vueltas_neumatico  tiempo_seg
4795       1     2.0   MEDIUM        0                  1     109.828
5973       1     3.0   MEDIUM        0                  2     110.141
7145       1     4.0   MEDIUM        0                  3     110.055
8333       1     5.0   MEDIUM        0                  4     110.138
9502       1     6.0   MEDIUM        0                  5     110.073
10630      1     7.0   MEDIUM        0                  6     110.146
11749      1     8.0   MEDIUM        0                  7     110.094
12870      1     9.0   MEDIUM        0                  8     110.609
14046      1    10.0   MEDIUM        0                  9     114.655
15321      1    11.0     HARD        1                  1     122.789
16467      1    12.0     HARD        1                  2     108.403
17622      1    13.0     HARD        1                  3     108.431
18762      1    14.0     HARD        1                  4     108.153
19883      1    15.0     HARD        1                  5     108.229
21010      1    16.0     HARD        1                  6     108.509
22145      1    17.0     HARD        1                  7     108.431
23275      1    18.0     HARD        1                  8     108.896
24400      1    19.0     HARD        1                  9     108.578
25532      1    20.0     HARD        1                 10     109.134
26655      1    21.0     HARD        1                 11     109.273

In [35]:
vueltas_con_neumaticos["PitCount"] = pd.to_numeric(
    vueltas_con_neumaticos["PitCount"],
    errors="coerce"
)

vueltas_con_neumaticos["es_pit"] = (
    vueltas_con_neumaticos
    .groupby("piloto")["PitCount"]
    .diff()
    .fillna(0)
    .gt(0)
)

print(vueltas_con_neumaticos["es_pit"].value_counts())

es_pit
False    785
True      34
Name: count, dtype: int64

In [36]:
vueltas_con_neumaticos[
    vueltas_con_neumaticos["es_pit"]
][
    ["piloto", "vuelta", "tiempo_seg", "PitCount", "Compound", "vueltas_neumatico"]
].head(20)

      piloto  vuelta  tiempo_seg  PitCount Compound  vueltas_neumatico
15321      1    11.0     122.789         1     HARD                  1
35826      1    29.0     120.489         2   MEDIUM                  1
14295     10    10.0     124.826         1     HARD                  1
36218     10    29.0     122.540         2     HARD                  1
16430     11    12.0     123.704         1   MEDIUM                  1
27964     11    22.0     121.831         2     HARD                  1
51851     11    43.0     123.523         3     SOFT                  1
18880     14    14.0     123.993         1     HARD                  1
17564     16    13.0     122.667         1     HARD                  1
32382     16    26.0     121.972         2     HARD                  1
17814     18    13.0     124.552         1     HARD                  1
13217      2     9.0     123.886         1   MEDIUM                  1
31862      2    25.0     123.841         2     HARD                  1
23626     20    18.0     124.382         1     HARD                  1
21369     22    16.0     124.840         1     HARD                  1
13094     23     9.0     123.191         1   MEDIUM                  1
30477     23    24.0     123.159         2     HARD                  1
12037     27     8.0     124.815         1     HARD                  1
27141     27    21.0     123.837         2   MEDIUM                  1
13134      3     9.0     123.019         1   MEDIUM                  1

In [37]:
datos_degradacion = vueltas_con_neumaticos[
    ~vueltas_con_neumaticos["es_pit"]
].copy()

print("Vueltas para analizar degradación:", len(datos_degradacion))
print(datos_degradacion[
    ["piloto", "vuelta", "Compound", "vueltas_neumatico", "tiempo_seg"]
].head(20))

Vueltas para analizar degradación: 785
      piloto  vuelta Compound  vueltas_neumatico  tiempo_seg
4795       1     2.0   MEDIUM                  1     109.828
5973       1     3.0   MEDIUM                  2     110.141
7145       1     4.0   MEDIUM                  3     110.055
8333       1     5.0   MEDIUM                  4     110.138
9502       1     6.0   MEDIUM                  5     110.073
10630      1     7.0   MEDIUM                  6     110.146
11749      1     8.0   MEDIUM                  7     110.094
12870      1     9.0   MEDIUM                  8     110.609
14046      1    10.0   MEDIUM                  9     114.655
16467      1    12.0     HARD                  2     108.403
17622      1    13.0     HARD                  3     108.431
18762      1    14.0     HARD                  4     108.153
19883      1    15.0     HARD                  5     108.229
21010      1    16.0     HARD                  6     108.509
22145      1    17.0     HARD                  7     108.431
23275      1    18.0     HARD                  8     108.896
24400      1    19.0     HARD                  9     108.578
25532      1    20.0     HARD                 10     109.134
26655      1    21.0     HARD                 11     109.273
27792      1    22.0     HARD                 12     108.448

In [38]:
degradacion = (
    datos_degradacion
    .groupby(["Compound", "vueltas_neumatico"])["tiempo_seg"]
    .agg(["mean", "count"])
    .reset_index()
)

degradacion.head(30)

   Compound  vueltas_neumatico        mean  count
0      HARD                  1  111.179500      2
1      HARD                  2  110.946370     27
2      HARD                  3  108.696037     27
3      HARD                  4  109.473407     27
4      HARD                  5  108.705538     26
5      HARD                  6  108.611385     26
6      HARD                  7  108.762808     26
7      HARD                  8  108.590154     26
8      HARD                  9  108.703192     26
9      HARD                 10  108.696154     26
10     HARD                 11  108.509692     26
11     HARD                 12  108.414269     26
12     HARD                 13  108.678538     26
13     HARD                 14  108.589500     24
14     HARD                 15  108.599952     21
15     HARD                 16  108.294421     19
16     HARD                 17  108.672353     17
17     HARD                 18  108.712625     16
18     HARD                 19  109.303929     14
19     HARD                 20  108.549500     10
20     HARD                 21  108.965444      9
21     HARD                 22  108.653286      7
22     HARD                 23  108.586571      7
23     HARD                 24  109.432833      6
24     HARD                 25  108.748200      5
25     HARD                 26  108.514000      5
26     HARD                 27  108.310400      5
27     HARD                 28  108.292500      4
28     HARD                 29  108.145500      4
29     HARD                 30  108.209000      3

In [39]:
tiempo_base = (
    datos_degradacion
    .groupby("Compound")["tiempo_seg"]
    .min()
    .reset_index()
    .rename(columns={"tiempo_seg": "tiempo_base"})
)

tiempo_base

  Compound  tiempo_base
0     HARD      105.563
1   MEDIUM      106.128
2     SOFT      104.701

In [40]:
datos_degradacion = datos_degradacion.merge(
    tiempo_base,
    on="Compound",
    how="left"
)

datos_degradacion["perdida_tiempo"] = (
    datos_degradacion["tiempo_seg"]
    - datos_degradacion["tiempo_base"]
)

datos_degradacion[
    [
        "piloto",
        "vuelta",
        "Compound",
        "vueltas_neumatico",
        "tiempo_seg",
        "tiempo_base",
        "perdida_tiempo"
    ]
].head(20)

,piloto,vuelta,Compound,vueltas_neumatico,tiempo_seg,tiempo_base,perdida_tiempo
0,1,2.0,MEDIUM,1,109.828,106.128,3.700
1,1,3.0,MEDIUM,2,110.141,106.128,4.013
2,1,4.0,MEDIUM,3,110.055,106.128,3.927
3,1,5.0,MEDIUM,4,110.138,106.128,4.010
4,1,6.0,MEDIUM,5,110.073,106.128,3.945
5,1,7.0,MEDIUM,6,110.146,106.128,4.018
6,1,8.0,MEDIUM,7,110.094,106.128,3.966
7,1,9.0,MEDIUM,8,110.609,106.128,4.481
8,1,10.0,MEDIUM,9,114.655,106.128,8.527
9,1,12.0,HARD,2,108.403,105.563,2.840
10,1,13.0,HARD,3,108.431,105.563,2.868
11,1,14.0,HARD,4,108.153,105.563,2.590
12,1,15.0,HARD,5,108.229,105.563,2.666
13,1,16.0,HARD,6,108.509,105.563,2.946
14,1,17.0,HARD,7,108.431,105.563,2.868
15,1,18.0,HARD,8,108.896,105.563,3.333
16,1,19.0,HARD,9,108.578,105.563,3.015
17,1,20.0,HARD,10,109.134,105.563,3.571
18,1,21.0,HARD,11,109.273,105.563,3.710
19,1,22.0,HARD,12,108.448,105.563,2.885

In [41]:
degradacion = (
    datos_degradacion
    .groupby(["Compound", "vueltas_neumatico"])["tiempo_seg"]
    .agg(["mean", "count"])
    .reset_index()
)

degradacion.head(30)

   Compound  vueltas_neumatico        mean  count
0      HARD                  1  111.179500      2
1      HARD                  2  110.946370     27
2      HARD                  3  108.696037     27
3      HARD                  4  109.473407     27
4      HARD                  5  108.705538     26
5      HARD                  6  108.611385     26
6      HARD                  7  108.762808     26
7      HARD                  8  108.590154     26
8      HARD                  9  108.703192     26
9      HARD                 10  108.696154     26
10     HARD                 11  108.509692     26
11     HARD                 12  108.414269     26
12     HARD                 13  108.678538     26
13     HARD                 14  108.589500     24
14     HARD                 15  108.599952     21
15     HARD                 16  108.294421     19
16     HARD                 17  108.672353     17
17     HARD                 18  108.712625     16
18     HARD                 19  109.303929     14
19     HARD                 20  108.549500     10
20     HARD                 21  108.965444      9
21     HARD                 22  108.653286      7
22     HARD                 23  108.586571      7
23     HARD                 24  109.432833      6
24     HARD                 25  108.748200      5
25     HARD                 26  108.514000      5
26     HARD                 27  108.310400      5
27     HARD                 28  108.292500      4
28     HARD                 29  108.145500      4
29     HARD                 30  108.209000      3

In [42]:
base_compuesto = (
    degradacion[degradacion["vueltas_neumatico"] <= 3]
    .groupby("Compound")["mean"]
    .mean()
    .reset_index()
    .rename(columns={"mean": "tiempo_base"})
)

base_compuesto

  Compound  tiempo_base
0     HARD   110.273969
1   MEDIUM   110.265383
2     SOFT   110.071333

In [45]:
base_stint = (
    datos_degradacion
    .groupby(["piloto", "PitCount", "Compound"])["tiempo_seg"]
    .transform("min")
)

datos_degradacion["tiempo_base_stint"] = base_stint

datos_degradacion["perdida_stint"] = (
    datos_degradacion["tiempo_seg"]
    - datos_degradacion["tiempo_base_stint"]
)

datos_degradacion[
    [
        "piloto",
        "vuelta",
        "Compound",
        "vueltas_neumatico",
        "tiempo_seg",
        "tiempo_base_stint",
        "perdida_stint"
    ]
].head(20)

,piloto,vuelta,Compound,vueltas_neumatico,tiempo_seg,tiempo_base_stint,perdida_stint
0,1,2.0,MEDIUM,1,109.828,109.828,0.000
1,1,3.0,MEDIUM,2,110.141,109.828,0.313
2,1,4.0,MEDIUM,3,110.055,109.828,0.227
3,1,5.0,MEDIUM,4,110.138,109.828,0.310
4,1,6.0,MEDIUM,5,110.073,109.828,0.245
5,1,7.0,MEDIUM,6,110.146,109.828,0.318
6,1,8.0,MEDIUM,7,110.094,109.828,0.266
7,1,9.0,MEDIUM,8,110.609,109.828,0.781
8,1,10.0,MEDIUM,9,114.655,109.828,4.827
9,1,12.0,HARD,2,108.403,107.431,0.972
10,1,13.0,HARD,3,108.431,107.431,1.000
11,1,14.0,HARD,4,108.153,107.431,0.722
12,1,15.0,HARD,5,108.229,107.431,0.798
13,1,16.0,HARD,6,108.509,107.431,1.078
14,1,17.0,HARD,7,108.431,107.431,1.000
15,1,18.0,HARD,8,108.896,107.431,1.465
16,1,19.0,HARD,9,108.578,107.431,1.147
17,1,20.0,HARD,10,109.134,107.431,1.703
18,1,21.0,HARD,11,109.273,107.431,1.842
19,1,22.0,HARD,12,108.448,107.431,1.017

In [46]:
degradacion_stint = (
    datos_degradacion
    .groupby(["Compound", "vueltas_neumatico"])["perdida_stint"]
    .agg(["median", "count"])
    .reset_index()
    .rename(columns={
        "median": "perdida_mediana"
    })
)

degradacion_stint.head(30)

   Compound  vueltas_neumatico  perdida_mediana  count
0      HARD                  1           0.7145      2
1      HARD                  2           0.5410     27
2      HARD                  3           0.7760     27
3      HARD                  4           0.8270     27
4      HARD                  5           1.0180     26
5      HARD                  6           1.1440     26
6      HARD                  7           1.0655     26
7      HARD                  8           0.9715     26
8      HARD                  9           1.1490     26
9      HARD                 10           1.1235     26
10     HARD                 11           0.8745     26
11     HARD                 12           0.8240     26
12     HARD                 13           0.9565     26
13     HARD                 14           0.8785     24
14     HARD                 15           0.8250     21
15     HARD                 16           0.6340     19
16     HARD                 17           0.6740     17
17     HARD                 18           0.6100     16
18     HARD                 19           0.8380     14
19     HARD                 20           0.6240     10
20     HARD                 21           0.7400      9
21     HARD                 22           0.5310      7
22     HARD                 23           0.7460      7
23     HARD                 24           0.8330      6
24     HARD                 25           0.7910      5
25     HARD                 26           0.5070      5
26     HARD                 27           0.6050      5
27     HARD                 28           0.3810      4
28     HARD                 29           0.3305      4
29     HARD                 30           0.5180      3

In [47]:
degradacion_modelo = degradacion_stint[
    degradacion_stint["count"] >= 5
].copy()

degradacion_modelo.head(30)

   Compound  vueltas_neumatico  perdida_mediana  count
1      HARD                  2           0.5410     27
2      HARD                  3           0.7760     27
3      HARD                  4           0.8270     27
4      HARD                  5           1.0180     26
5      HARD                  6           1.1440     26
6      HARD                  7           1.0655     26
7      HARD                  8           0.9715     26
8      HARD                  9           1.1490     26
9      HARD                 10           1.1235     26
10     HARD                 11           0.8745     26
11     HARD                 12           0.8240     26
12     HARD                 13           0.9565     26
13     HARD                 14           0.8785     24
14     HARD                 15           0.8250     21
15     HARD                 16           0.6340     19
16     HARD                 17           0.6740     17
17     HARD                 18           0.6100     16
18     HARD                 19           0.8380     14
19     HARD                 20           0.6240     10
20     HARD                 21           0.7400      9
21     HARD                 22           0.5310      7
22     HARD                 23           0.7460      7
23     HARD                 24           0.8330      6
24     HARD                 25           0.7910      5
25     HARD                 26           0.5070      5
26     HARD                 27           0.6050      5
34   MEDIUM                  1           0.9410     17
35   MEDIUM                  2           0.3130     25
36   MEDIUM                  3           0.2270     25
37   MEDIUM                  4           0.2670     25

In [53]:
def calcular_degradacion(compuesto, vueltas_neumatico):
    modelo = degradacion_final[compuesto]
    
    return (
        modelo["intercepto"]
        + modelo["pendiente"] * vueltas_neumatico
    )

In [55]:
tiempo_base_compuesto = (
    datos_degradacion
    .groupby("Compound")["tiempo_base_stint"]
    .median()
)

tiempo_base_compuesto

Compound
HARD      107.845
MEDIUM    109.702
SOFT      110.314
Name: tiempo_base_stint, dtype: float64

In [56]:
def calcular_tiempo_vuelta(compuesto, vueltas_neumatico):
    tiempo_base = tiempo_base_compuesto[compuesto]
    perdida = calcular_degradacion(compuesto, vueltas_neumatico)
    
    return tiempo_base + perdida

In [58]:
vueltas_pit = vueltas_con_neumaticos[
    vueltas_con_neumaticos["es_pit"]
].copy()

vueltas_pit[
    [
        "piloto",
        "vuelta",
        "tiempo_seg",
        "PitCount",
        "Compound"
    ]
].head(30)

      piloto  vuelta  tiempo_seg  PitCount Compound
15321      1    11.0     122.789         1     HARD
35826      1    29.0     120.489         2   MEDIUM
14295     10    10.0     124.826         1     HARD
36218     10    29.0     122.540         2     HARD
16430     11    12.0     123.704         1   MEDIUM
27964     11    22.0     121.831         2     HARD
51851     11    43.0     123.523         3     SOFT
18880     14    14.0     123.993         1     HARD
17564     16    13.0     122.667         1     HARD
32382     16    26.0     121.972         2     HARD
17814     18    13.0     124.552         1     HARD
13217      2     9.0     123.886         1   MEDIUM
31862      2    25.0     123.841         2     HARD
23626     20    18.0     124.382         1     HARD
21369     22    16.0     124.840         1     HARD
13094     23     9.0     123.191         1   MEDIUM
30477     23    24.0     123.159         2     HARD
12037     27     8.0     124.815         1     HARD
27141     27    21.0     123.837         2   MEDIUM
13134      3     9.0     123.019         1   MEDIUM
28207      3    22.0     124.465         2     HARD
17755     31    13.0     123.593         1     HARD
38404     31    31.0     122.496         2     HARD
21068      4    16.0     121.761         1     HARD
36953      4    30.0     120.262         2     HARD
16397     44    12.0     124.792         1     HARD
33475     44    27.0     121.300         2     HARD
26716     55    21.0     122.634         1   MEDIUM
35900     55    29.0     121.610         2     HARD
15292     63    11.0     122.456         1     HARD

In [60]:
vueltas_pit = vueltas_con_neumaticos[
    (vueltas_con_neumaticos["es_pit"]) &
    (vueltas_con_neumaticos["Compound"].isin(["HARD", "MEDIUM"]))
].copy()

vueltas_pit["tiempo_estimado"] = vueltas_pit.apply(
    lambda fila: calcular_tiempo_vuelta(
        fila["Compound"],
        fila["vueltas_neumatico"]
    ),
    axis=1
)

vueltas_pit["perdida_pit_aprox"] = (
    vueltas_pit["tiempo_seg"]
    - vueltas_pit["tiempo_estimado"]
)

vueltas_pit[
    [
        "piloto",
        "vuelta",
        "Compound",
        "tiempo_seg",
        "tiempo_estimado",
        "perdida_pit_aprox"
    ]
].head(20)

      piloto  vuelta Compound  tiempo_seg  tiempo_estimado  perdida_pit_aprox
15321      1    11.0     HARD     122.789       108.848247          13.940753
35826      1    29.0   MEDIUM     120.489       110.085096          10.403904
14295     10    10.0     HARD     124.826       108.848247          15.977753
36218     10    29.0     HARD     122.540       108.848247          13.691753
16430     11    12.0   MEDIUM     123.704       110.085096          13.618904
27964     11    22.0     HARD     121.831       108.848247          12.982753
18880     14    14.0     HARD     123.993       108.848247          15.144753
17564     16    13.0     HARD     122.667       108.848247          13.818753
32382     16    26.0     HARD     121.972       108.848247          13.123753
17814     18    13.0     HARD     124.552       108.848247          15.703753
13217      2     9.0   MEDIUM     123.886       110.085096          13.800904
31862      2    25.0     HARD     123.841       108.848247          14.992753
23626     20    18.0     HARD     124.382       108.848247          15.533753
21369     22    16.0     HARD     124.840       108.848247          15.991753
13094     23     9.0   MEDIUM     123.191       110.085096          13.105904
30477     23    24.0     HARD     123.159       108.848247          14.310753
12037     27     8.0     HARD     124.815       108.848247          15.966753
27141     27    21.0   MEDIUM     123.837       110.085096          13.751904
13134      3     9.0   MEDIUM     123.019       110.085096          12.933904
28207      3    22.0     HARD     124.465       108.848247          15.616753

In [61]:
costo_pit_aprox = vueltas_pit["perdida_pit_aprox"].median()

print("Costo aproximado del pit stop:", round(costo_pit_aprox, 2), "segundos")

Costo aproximado del pit stop: 13.75 segundos

In [62]:
COSTO_PIT = costo_pit_aprox

def simular_estrategia(total_vueltas, estrategia):
    """
    Simula una estrategia de carrera.

    estrategia:
        lista de tuplas (compuesto, cantidad_de_vueltas)
    """

    tiempo_total = 0
    paradas = 0

    for compuesto, cantidad_vueltas in estrategia:

        for edad_neumatico in range(1, cantidad_vueltas + 1):
            tiempo_total += calcular_tiempo_vuelta(
                compuesto,
                edad_neumatico
            )

        paradas += 1

    # No hay parada después del último stint
    paradas -= 1

    tiempo_total += paradas * COSTO_PIT

    return tiempo_total

In [69]:
resultados_estrategias = []

for vuelta_pit in range(10, 36):

    vueltas_medium = vuelta_pit
    vueltas_hard = 44 - vuelta_pit

    estrategia = [
        ("MEDIUM", vueltas_medium),
        ("HARD", vueltas_hard)
    ]

    tiempo_total = simular_estrategia(
        44,
        estrategia
    )

    resultados_estrategias.append({
        "vuelta_pit": vuelta_pit,
        "vueltas_medium": vueltas_medium,
        "vueltas_hard": vueltas_hard,
        "tiempo_total": tiempo_total
    })

resultados_estrategias = pd.DataFrame(resultados_estrategias)

resultados_estrategias.head()

   vuelta_pit  vueltas_medium  vueltas_hard  tiempo_total
0          10              10            34   4817.446656
1          11              11            33   4819.128701
2          12              12            32   4820.855266
3          13              13            31   4822.626350
4          14              14            30   4824.441954

In [70]:
mejor_estrategia = resultados_estrategias.loc[
    resultados_estrategias["tiempo_total"].idxmin()
]

print(mejor_estrategia)

vuelta_pit          10.000000
vueltas_medium      10.000000
vueltas_hard        34.000000
tiempo_total      4817.446656
Name: 0, dtype: float64